### ISSUE TITLE
controller accessing the etcdserver  encounters  "user name is empty" error

### ISSUE THREAD

**Issue by bbqccx** [apache/kvrocks-controller#101]
{"level":"error","ts":1690943813.5158186,"caller":"etcd/etcd.go:231","msg":"Failed to acquire the leader campaign","error":"etcdserver: user name is empty","stacktrace":"github.com/RocksLabs/kvrocks_controller/storage/persistence/etcd.(*Etcd).electLoop\n\t/controller/kvrocks_controller/storage/persistence/etcd/etcd.go:231"}
{"level":"warn","ts":1690943813.5533369,"caller":"v3@v3.5.4/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc0006ae1c0/127.0.0.1:2379","attempt":0,"error":"rpc error: code = InvalidArgument desc = etcdserver: user name is empty"}

version 0.2.0

**Comment by bbqccx** [comment]
test ok

**Comment by git-hulk** [comment]
Thanks for your feedback!
