### ISSUE TITLE
分片存在一主2从情况下，切换多次后容易出现信息提示有2个master

### ISSUE THREAD

**Issue by bbqccx** [apache/kvrocks-controller#103]
通过controller的api可以对shard配置1主2从的副本模式，多次模拟master节点故障切换后会出现controller侧显示2主1从，从kvrocks节点上看仍只有1主2从。
尝试从api删除controller侧显示为master但实际为slave的kvrocks节点会报错提示，still some slots in this shard, please migrate them first"。
最终只能在管控上将该cluster删除，但是删除后现有管控版本无法重新加载已有集群，故需要https://github.com/RocksLabs/kvrocks_controller/issues/102中加载已有集群配置功能。

**Comment by bbqccx** [comment]
test ok
1.Normal  master switch when one node fails
2.all master-slave nodes on a single shard are shut down and restarted,
 the problem has not reoccurred

**Comment by git-hulk** [comment]
Thank you for your feedback!
