### ISSUE TITLE
network with 100% packet loss and process hang scenarios cannot switch quickly

### ISSUE THREAD

**Issue by bbqccx** [apache/kvrocks-controller#105]
Based on our test results, in scenarios where the master node experiences 100% packet loss and process hang, it cannot switch quickly. Each probe takes about 1 minute to time out, which causes a 15 * 3 second switch to take 15 minutes to occur。
suggest setting the timeout time for each probe to 2 to 3 seconds, so that even in extreme scenarios, problems can be detected as early as possible and control can initiate the switch proactively。

**Comment by git-hulk** [comment]
@bbqccx Thanks for your feedback, will fix it soon.

**Comment by bbqccx** [comment]
readTimeout  = 3 * time.Second  writeTimeout = 3 * time.Second
 
test ok

**Comment by git-hulk** [comment]
Thank you!
