### ISSUE TITLE
MinAliveSize and MaxFailureRatio  lead failover in safe mode

### ISSUE THREAD

**Issue by bbqccx** [apache/kvrocks-controller#108]
in my case, i have two computer, one computer have 8 kvrocks node, cluster have 16 nodes。
when one computer carsh or broken ， then failover will in safe mode， "msg":"safe mode, loop ratio 0.40, allnodes: 16, failnodes: 7"
beause MinAliveSize is 10，MaxFailureRatio is 0.4，failove will check "nodesCount > MinAliveSize && float64(len(c.tasks))/float64(nodesCount) > MaxFailureRatio"

We would like to be able to configure MinAliveSize and MaxFailureRatio through conf file

**Comment by git-hulk** [comment]
Thank you! To see if @uds5501 would like to take this.

**Comment by uds5501** [comment]
Sure mas, will take a look into it!

**Comment by git-hulk** [comment]
Thanks @uds5501, don't hesitate to contact me if you have any question.
