### ISSUE TITLE
Unix timestamp in the log  modify to  time in the corresponding timezone

### ISSUE THREAD

**Issue by bbqccx** [apache/kvrocks-controller#112]
{"level":"info","ts":1693818282.8894243,"caller":"server/main.go:75","msg":"Kvrocks controller is running with version: unstable"}
when "ts":1693818282.8894243  convert to 2023/9/4 17:4:42 in log ，It may be easier to read

**Comment by git-hulk** [comment]
Done in unstable branch, please have a try.
