### ISSUE TITLE
go mod checksum mismatch

### ISSUE THREAD

**Issue by wsehjk** [apache/kvrocks-controller#152]
The verison (1.7.3) of `github.com/gin-gonic/gin` causes checksum mismatch error.
```bash
verifying github.com/gin-gonic/gin@v1.7.3: checksum mismatch
        downloaded: h1:3U500Wp728rATEiFJtk1L7dhAbWobNDQC0Cbd4yhhdc=
        go.sum:     h1:aMBzLJ/GMEYmv1UWs2FFTcPISLrQH2mRgL9Glz8xows=

SECURITY ERROR
This download does NOT match an earlier download recorded in go.sum.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.
```
This can not be fixed by running `rm go.sum`, `go clean -modcache`, `go mod tidy`
References are here [https://github.com/gin-gonic/gin/issues/2806](), [https://github.com/gin-gonic/gin/releases/tag/v1.7.4]()

As suggested, use v1.7.4 instead of v1.7.3

**Comment by jihuayu** [comment]
Hi @wsehjk. 
> As suggested, use v1.7.4 instead of v1.7.3

Thanks for your suggestion! 
Can you send a PR to fix this issue?
