### ISSUE TITLE
Deleting a cluster through the controller API interface does not take effect

### ISSUE THREAD

**Issue by pangtujun** [apache/kvrocks-controller#156]
Calling the delete cluster interface to delete the cluster, the kvrocks cluster can still be accessed, and the node.conf file of the kvrocks node is still present, but the kvrocks node has not been reset

Delete/app/v1/namespaces/{namespace}/clusters/{cluster}

**Comment by git-hulk** [comment]
@pangtujun Thanks for your feedback, will take a look soon.

**Comment by git-hulk** [comment]
@pangtujun It's an expected behavior, we don't want to delete cluster information from the nodes for now. But you can use `CLUSTER RESET` to do that.
