### ISSUE TITLE
Kvrocks Controller failover didn't work as expeceted

### ISSUE THREAD

**Issue by QQxiaoyuyu** [apache/kvrocks-controller#157]
首先我启动了3个kvctlser,其中一个leader，2个slave，这三个可以正常切换，然后我又增加了3个kvctlser，将起初的3个kvctlser停掉，新的kvctlser都变成了leader，但是都可以正常接收请求。我把新的3个kvctlser停止，把开始的3个kvctlser启动，仍然是1个leader，2个slave，且可以正常切换，请帮忙看看新增的kvctlser为什么不能替换旧的kvctlser

**Comment by git-hulk** [comment]
@QQxiaoyuyu Thanks for your feedback, will take a look when I get time.

**Comment by QQxiaoyuyu** [comment]
问题已经找到，由于我新的三个addr 配置的都是0.0.0.0:9379,这个addr可以配置多个地址吗

**Comment by git-hulk** [comment]
现在默认是用 addr 作为 ID，所以必须是配置具体的机器 IP。这个可以优化一下，避免配置 0.0.0.0 导致冲突

**Comment by QQxiaoyuyu** [comment]
嗯，我明白，主要现在我们想用api的话，需要用外网进行访问，内网访问需要走vpn，比较麻烦，我现在是使用不同的端口来进行区别了

**Comment by bbqccx** [comment]
看下这个，很早社区就说明过。https://github.com/apache/kvrocks-controller/issues/104

**Comment by git-hulk** [comment]
@QQxiaoyuyu @bbqccx Will be fixed in #160

**Comment by QQxiaoyuyu** [comment]
好的，加油
