### ISSUE TITLE
The test found that the detection command connecting to kvrocks would continuously create new connections, but would not close the connections established each time, resulting in a full connection count for kvrocks.

### ISSUE THREAD

**Issue by sj1385** [apache/kvrocks-controller#176]
use version：0.3.1
The test found that the detection command connecting to kvrocks would continuously create new connections, but would not close the connections established each time, resulting in a full connection count for kvrocks.

**Comment by git-hulk** [comment]
@sj1385 Thanks for your report, would you mind having a try at the unstable branch version.
