### ISSUE TITLE
Incompatible etcd version error

### ISSUE THREAD

**Issue by CulturalProfessor** [apache/kvrocks-controller#180]
While running `make setup` I got this error if we're using `etcd:latest` in docker-compose.yml, as @jihuayu mentioned it might be due to some incompatibility with docker and docker image.
 
![unnamed](https://github.com/apache/kvrocks-controller/assets/92238941/f539fe6e-f3f2-4fbf-bdf6-fc7c291272ca)

to fix it I had to use a specific version like `etcd:v3.5.13`.

![image](https://github.com/apache/kvrocks-controller/assets/92238941/6dba64bd-37ec-4367-b731-f0955e3b3ebb)

**Comment by git-hulk** [comment]
@CulturalProfessor Yes, we should use the v3.5.13 instead of the [etcd latest](https://quay.io/repository/coreos/etcd?tab=tags&tag=latest) which is an older version. Would you like to create a PR to resolve this?

**Comment by CulturalProfessor** [comment]
> @CulturalProfessor Yes, we should use the v3.5.13 instead of the [etcd latest](https://quay.io/repository/coreos/etcd?tab=tags&tag=latest) which is an older version. Would you like to create a PR to resolve this?

sure will update it
