### ISSUE TITLE
slot range lost, there will be fields[9] slot range if a master did slot and data migration before

### ISSUE THREAD

**Issue by greatsharp** [apache/kvrocks-controller#184]
https://github.com/apache/kvrocks-controller/blob/3a336a9b88faaef3678f2cfcdf81f67ae23d9d14/store/cluster.go#L277

node string will like
xxxx ip:6666@xxx master - timestamp timestamp 117 connected 0-123 124-5460

**Comment by git-hulk** [comment]
@greatsharp Thanks for your report.
