### ISSUE TITLE
error returned if set preferred_node_id param, report {"error":{"message":"EOF"},"data":null}

### ISSUE THREAD

**Issue by greatsharp** [apache/kvrocks-controller#195]
https://github.com/apache/kvrocks-controller/blob/8fc7804c0d624ac4d0434f93622148dd2d297d73/server/api/shard.go#L131C4-L134C5

suggest change c.BindJson to json.Unmarshal

**Comment by git-hulk** [comment]
@greatsharp Makes sense, would you like to submit a PR to resolve this?

**Comment by greatsharp** [comment]
> @greatsharp Makes sense, would you like to submit a PR to resolve this?

can not submit any code to github due to some reason :-(
