### ISSUE TITLE
parallel probe nodes give rise to goroutine leak

### ISSUE THREAD

**Issue by greatsharp** [apache/kvrocks-controller#200]
https://github.com/apache/kvrocks-controller/blob/f3a58b9bb7b26d8137454ffff7b2b1496c81e3b5/controller/cluster.go#L199C4-L228C14

test a scenario, 3000 clusters, 9 node with fake IP address per cluster, continuously report 'Failed to probe the node' error.
at this time, goroutines number is more than 380000.

**Comment by git-hulk** [comment]
@greatsharp I didn't quite understand your point, can you elaborate a bit on how it leaks go routines?
