### ISSUE TITLE
migrate slot 16383, report "slot out of range"

### ISSUE THREAD

**Issue by greatsharp** [apache/kvrocks-controller#207]
https://github.com/apache/kvrocks-controller/blob/f3a58b9bb7b26d8137454ffff7b2b1496c81e3b5/store/cluster.go#L167C1-L169C3

**Comment by greatsharp** [comment]
">= MaxSlotID" should be "> MaxSlotID"

**Comment by git-hulk** [comment]
@greatsharp Good catch. Will fix it soon.
