### ISSUE TITLE
Suggest to  check migrate status only in main controller

### ISSUE THREAD

**Issue by greatsharp** [apache/kvrocks-controller#227]
https://github.com/apache/kvrocks-controller/blob/bdfe415a9e7809628e472f07a95117d6d6b73156/controller/cluster.go#L329C1-L335C46

Suggest to  check migrate status only in main controller, it is not necessarily checking in slave controller, it can also avoid slave controllers update slots of cluster info concurrently.

**Comment by git-hulk** [comment]
@greatsharp From the current implementation, the cluster checker will be closed once the controller node becomes non-leader via `suspend()`. Did I miss anything?

**Comment by git-hulk** [comment]
I didn't reproduce this issue on my side, welcome to reopen if this problem still living.

**Comment by greatsharp** [comment]
I see, no problem now
