### ISSUE TITLE
Allow to add/remove a peer via HTTP API

### ISSUE THREAD

**Issue by git-hulk** [apache/kvrocks-controller#231]

**Comment by jihuayu** [comment]
I have 2 questuions.
1. Do we need to set the default storage_type to raft? 
2. After modifying the peers via the command line, do we need to synchronize the changes in the configuration file?

**Comment by git-hulk** [comment]
> Do we need to set the default storage_type to raft?

Maybe we could mark it as an experiment feature at the next release, and then become the default one after that.

> After modifying the peers via the command line, do we need to synchronize the changes in the configuration file?

Yes, it would be better to do that. And it's nice to have, but not required.

**Comment by jihuayu** [comment]
Where does the manager's Raft node reside in the controller's abstraction? 
In my understanding, we shouldn't directly call the underlying storage engine's AddPeer method in the API (as this would break the encapsulation of the Store). 
Should we add an AddPeer/RemovePeer abstraction to the Store? Do you have any good ideas? @git-hulk

**Comment by git-hulk** [comment]
> Should we add an AddPeer/RemovePeer abstraction to the Store? Do you have any good ideas? @git-hulk

Yes, I'm happy with this proposal since I cannot come up with a better way.
