### ISSUE TITLE
Missing some instructions like the add node/shard and migration?

### ISSUE THREAD

**Issue by vearne** [apache/kvrocks-controller#70]
- Add a new node for the cluster
```
redis-cli --cluster add-node
```

- Rebalance and migration
```
redis-cli --cluster reshard
```

**Comment by git-hulk** [comment]
@vearne Please use English to describe the issue, it would be more friendly to users who don't understand Chinese.

**Comment by vearne** [comment]
ok

**Comment by git-hulk** [comment]
Hi @vearne 

I created another issues to track this and will close it.
