### ISSUE TITLE
Don't allow one node to be appeared in multiple clusters

### ISSUE THREAD

**Issue by git-hulk** [apache/kvrocks-controller#81]
Currently, we didn't check if the node has already been added to other clusters and it may cause data loss if the user falsely adds the node to multiple clusters.

**Comment by Yangsx-1** [comment]
I‘d like to help with this. But i'm not very familiar with go and this task. It may take some time. :)

**Comment by git-hulk** [comment]
@Yangsx-1 Thanks, assigned. Feel free to ask any questions if you are uncertain.
