### ISSUE TITLE
Show the node status in when listing nodes

### ISSUE THREAD

**Issue by bbqccx** [apache/kvrocks-controller#88]
test/cluster-test1/0>> ls
+------------------------------------------+----------------+--------+--------+--------+---------+
| ID                                       | IP:PORT        | ROLE   | SLOTS  | IMPORT | MIGRATE |
+------------------------------------------+----------------+--------+--------+--------+---------+
| J5xjIHFKJIp0fxdtDr7VpRLfAWeWHjnPK0PQH9lI | 127.0.0.1:8021 | master | 0-8191 |     -1 |      -1 |
| 0wYMN4r6rSytnS33Rv5Z032GE1wctQFF6d8yIWDJ | 127.0.0.1:8022 | slave  | 0-8191 |     -1 |      -1 |
+------------------------------------------+----------------+--------+--------+--------+---------+

Can add a field to show whether the node status is health or not

**Comment by krishnaduttPanchagnula** [comment]
can take it up. Please assign

**Comment by git-hulk** [comment]
@krishnaduttPanchagnula Thank you! Assigned.
