### ISSUE TITLE
Don't allow to create the cluster if the node has been initialized

### ISSUE THREAD

**Issue by git-hulk** [apache/kvrocks-controller#92]
Currently, we didn't check if the node has been initialized and it may regenerate the node id for it. This would cause the node id was mismatched the cluster topology.

**Comment by yeyypp** [comment]
Hi,Does this issuee mean in the server/cluster.go Create function, we should check if storage exist a node with the same Addr as the req.Nodes?

**Comment by git-hulk** [comment]
@yeyypp We would like to check if the node has been initialized when creating. That's to say, if a node has the cluster information, then it cannot be joined as a new node.
