### ISSUE TITLE
Move kvrocks_controller into the apache organization

### ISSUE THREAD

**Issue by git-hulk** [apache/kvrocks-controller#94]
Hi contributors

We plan to move this project into the Apache organization as a sub-project of the [kvrocks](https://github.com/apache/kvrocks). Does this sound good to you? if yes, please leave a comment like +1 or LGTM. If not, please leave a comment, and we would also discuss about how to handle this.

cc @rfyiamcool @vearne @ColinChamber @krishnaduttPanchagnula @limingzju @joeylichang @Venjy @hbpen

**Comment by Venjy** [comment]
+1
Sound good!

**Comment by hbpen** [comment]
+1

**Comment by krishnaduttPanchagnula** [comment]
lgtm

**Comment by rfyiamcool** [comment]
👍

**Comment by rfyiamcool** [comment]
+1

**Comment by MateSousa** [comment]
@git-hulk how can i move my contribute to the Apache group??

**Comment by git-hulk** [comment]
@MateSousa Simply reply +1 or LGTM. I will raise the proposal to move if all are good for this.

**Comment by MateSousa** [comment]
lgtm

**Comment by ColinChamber** [comment]
+1
best

**Comment by git-hulk** [comment]
Thanks all, I will send the proposal recently, other guys who have any comments can feedback here.
