### ISSUE TITLE
Use dns name for nodes 

### ISSUE THREAD

**Issue by paragor** [apache/kvrocks-controller#96]
https://github.com/RocksLabs/kvrocks_controller/blob/ef4a9453ea1a0adb84232769b4187ea0813687b0/server/cluster.go#L44

There is restriction - cluster's nodes should set by ip in config. But in k8s env kvrocks more often run as statefulset with static DNS name and dynamic IP address.

So, it would be cool if the controller could use dns names instead if ip addresses.

**Comment by git-hulk** [comment]
Hi @paragor 

Thanks for your feedback, will fix this in the next version.

**Comment by MateSousa** [comment]
can i do it?

**Comment by git-hulk** [comment]
@MateSousa Definitely yes, thanks for your interest.
